const router = require("express").Router();

// Getting the client
const { PrismaClient } = require("@prisma/client");

// The models/schemas are generated by npx prisma generate so we can import the models directly from the instance
const { user } = new PrismaClient();

router.get("/", async (req, res) => {
  // Query with select and where clause
  //   const users = user.findMany({
  //     select: {
  //       username: true.valueOf,
  //       posts: true,
  //     },
  //     where: {
  //       username: "test",
  //     },
  //   });

  const users = await user.findMany({
    select: {
      username: true,
      posts: true,
    },
  });

  res.json(users);
});

// Create user

router.post("/", async (req, res) => {
  const { username } = req.body;

  const userExists = await user.findUnique({
    where: {
      username,
    },
    select: {
      username: true,
    },
  });

  if (userExists) {
    return res.status(401).json({ error: "User already exists" });
  }

  // Create the user using .create()

  const newUser = await user.create({
    data: {
      username,
    },
    // Select returns only the selected fields after create
    select: {
      username: true,
    },
  });

  res.json(newUser);
});

module.exports = router;
